export default function Privacy() {
  return (
    <main className="min-h-screen bg-white py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-display font-bold text-gray-900 mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: June 2025</p>

        {[
          {
            title: "What we collect",
            body: "SpendWise AI collects: your name and email address at registration; expense, budget, and goal data you enter; and conversation history with AI agents. We do not collect payment information because the app is free.",
          },
          {
            title: "How we use your data",
            body: "Your financial data is used exclusively to power AI features within your own account. We read your expenses, budgets, and goals to generate personalized AI responses. We never use your data to train AI models, sell to third parties, or share with advertisers.",
          },
          {
            title: "Data security",
            body: "Passwords are hashed with bcrypt before storage and are never readable by anyone, including us. API keys (including your Anthropic key) are stored only on the server and never exposed to the client. JSON Web Tokens expire after 7 days. All communication is over HTTPS.",
          },
          {
            title: "Third-party AI",
            body: "AI responses are generated by Claude (Anthropic). Your financial data is sent to Anthropic's API to generate responses. Anthropic's privacy policy governs how they handle API data. We send only the minimum data needed for each request.",
          },
          {
            title: "Data deletion",
            body: "You can delete your account and all associated data at any time by contacting hello@spendwise.ai. We will permanently delete your data within 7 business days.",
          },
          {
            title: "Cookies",
            body: "SpendWise AI uses a single localStorage item to store your authentication token. We do not use tracking cookies, analytics cookies, or advertising cookies.",
          },
          {
            title: "Contact",
            body: "For privacy questions or deletion requests, email hello@spendwise.ai.",
          },
        ].map((section) => (
          <div key={section.title} className="mb-8">
            <h2 className="text-lg font-display font-bold text-gray-900 mb-2">{section.title}</h2>
            <p className="text-sm text-gray-600 leading-relaxed">{section.body}</p>
          </div>
        ))}
      </div>
    </main>
  );
}
